import './index.css';
import Header from '../components/Header';
//import { CartContextProvider } from '@/context/CartContext';
import { ProductsProvider } from "@/context/products_context";
import { FilterProvider } from "@/context/filter_context";
import { CartProvider } from "@/context/cart_context";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <ProductsProvider>
        <FilterProvider>
          <CartProvider>
            <ToastContainer />
              <Header />
              {children}
            </CartProvider>
          </FilterProvider>
        </ProductsProvider>
      </body>
    </html>
  )
}
