import './index.css';
import Header from '../components/Header';
//import { CartContextProvider } from '@/context/CartContext';
import CartProvider from '@/providers/CartProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
         <ToastContainer />
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}
