import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Suspense } from 'react';
import { ProductsProvider } from "@/context/products_context";
import { FilterProvider } from "@/context/filter_context";
import { CartProvider } from "@/context/cart_context";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { locales } from "@/app/i18n/settings";

export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type RootLayoutProps = {
  children: React.ReactNode;
  params: { locale: string };
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  const locale = params.locale;

  return (
  <ProductsProvider>
    <FilterProvider>  
      <CartProvider>
        <ToastContainer />
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
        </Suspense>
          {children}
          <Footer />
        </CartProvider>
      </FilterProvider>
    </ProductsProvider>
  )
}
