import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Suspense } from 'react';
// import { ProductsProvider } from "@/context/products_context";
// import { FilterProvider } from "@/context/filter_context";
// import { CartProvider } from "@/context/cart_context";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { locales } from "@/app/i18n/settings";
//import { ApolloProvider } from "@apollo/client";
//import { useApollo } from "@/lib/apolloClient";
import { ApolloWrapper } from "@/lib/apolloClient";

//import { store } from '@/redux/store';
//import { Provider } from 'react-redux';

import StoreProvider from '@/redux/StoreProvider';
import ClientSessionProvider from '@/components/ClientSessionProvider';


export async function generateStaticParams() {
  return locales.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

type RootLayoutProps = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout(props: RootLayoutProps) {
  const params = await props.params;

  const {
    children
  } = props;

  const locale = params.locale;
  //const apolloClient = useApollo();

  return (
    <StoreProvider>

      <ApolloWrapper>
     
        <ToastContainer />
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
        </Suspense>
        <ClientSessionProvider>
          {children}
        </ClientSessionProvider>
        <Footer />
     
      {/* <ProductsProvider>
        <FilterProvider>  
          <CartProvider>
            <ToastContainer />
            <Suspense fallback={<div>Loading...</div>}>
              <Header />
            </Suspense>
              {children}
            <Footer />
          </CartProvider>
         </FilterProvider>
      </ProductsProvider> */}
      </ApolloWrapper>
    </StoreProvider>
  )
}
